<?php
include_once "strings/translations.php";
/**
 * Display the invite to show progress
 * @return void
 */
function displayInviteShowProgress(){
    echo "<td colspan='2'>" . displayInvite(getString("invite_action_show_progress")) . "</td>";
}

/**
 * Display an extra badge
 * @param string $key String key
 * @return void
 */
function displayExtraBadge(string $key, bool $value){
    echo "
        <tr" . ($value ? " class=\"green\"" : "") . ">
            <td><img src=\"svg/$key.svg\" alt=\"" . getString($key) . "\" title=\"" . getString($key) . "\"></td>
            <td>" . getString($key) . "</td>
        </tr>
    ";
}

/**
 * Transform "Top xx%" into a value
 * @param float $percentage the percentage to check (ex. 10 for Top 10%)
 * @param string $sql the SQL query to execute
 * @return int the value
 */
function topPercentToValue(float $percentage, string $sql){
    $rawSQL = arraySQL($sql . ";");
    $count = $rawSQL?count($rawSQL):0;
    $offset = floor($count * $percentage / 100) - 1;
    if($offset < 0) return PHP_INT_MAX;
    return intSQL($sql . " LIMIT 1 OFFSET " . $offset . ";");
}

//Arrays
//Goals are defined here
$streak_badges = [7, 14, 30, 365];
$points_top = [10, 5, 1, 0.1];
$predictionsCreated_top = [10, 5, 1, 0.1];
$bets_top = [10, 5, 1, 0.1];
$pointsSpent_top = [10, 5, 1, 0.1];
$betsWon_top = [10, 5, 1, 0.1];
//Autogenerated arrays
$points_sql = "SELECT `points` FROM `users` ORDER BY `points` DESC";
$points_badges = [];
foreach($points_top as $top){
    array_push($points_badges, topPercentToValue($top, $points_sql));
}
$predictionsCreated_sql = "SELECT `predictionsCreated` FROM `users` LEFT JOIN (SELECT `user`, COUNT(*) AS `predictionsCreated` FROM `predictions` GROUP BY `user`) `predictions2` ON `users`.`username` = `predictions2`.`user` ORDER BY `predictionsCreated` DESC";
$predictionsCreated_badges = [];
foreach($predictionsCreated_top as $top){
    array_push($predictionsCreated_badges, topPercentToValue($top, $predictionsCreated_sql));
}
$bets_sql = "SELECT `bets` FROM `users` LEFT JOIN (SELECT `user`, COUNT(*) AS `bets` FROM `votes` GROUP BY `user`) `votes2` ON `users`.`username` = `votes2`.`user` ORDER BY `bets` DESC";
$bets_badges = [];
foreach($bets_top as $top){
    array_push($bets_badges, topPercentToValue($top, $bets_sql));
}
$pointsSpent_sql = "SELECT `pointsSpent` FROM `users` LEFT JOIN (SELECT `user`, SUM(`points`) AS `pointsSpent` FROM `votes` GROUP BY `user`) `votes2` ON `users`.`username` = `votes2`.`user` ORDER BY `pointsSpent` DESC";
$pointsSpent_badges = [];
foreach($pointsSpent_top as $top){
    array_push($pointsSpent_badges, topPercentToValue($top, $pointsSpent_sql));
}
$betsWon_sql = "SELECT `correct_vote_count` FROM `users` LEFT JOIN (SELECT votes.user, COUNT(*) AS correct_vote_count FROM votes JOIN predictions ON votes.prediction = predictions.id WHERE votes.choice = predictions.answer GROUP BY votes.user) correct_votes ON users.username = correct_votes.user ORDER BY `correct_vote_count` DESC";
$betsWon_badges = [];
foreach($betsWon_top as $top){
    array_push($betsWon_badges, topPercentToValue($top, $betsWon_sql));
}

//Initializations
$streak = 0;
$streakCurrentBadgeLevel = "";
$streakNextBadgeLevel = "";

$points = 0;
$pointsCurrentBadgeLevel = "";
$pointsNextBadgeLevel = "";

$predictionsCreated = 0;
$predictionsCreatedCurrentBadgeLevel = "";
$predictionsCreatedNextBadgeLevel = "";

$bets = 0;
$betsCurrentBadgeLevel = "";
$betsNextBadgeLevel = "";

$pointsSpent = 0;
$pointsSpentCurrentBadgeLevel = "";
$pointsSpentNextBadgeLevel = "";

$betsWon = 0;
$betsWonCurrentBadgeLevel = "";
$betsWonNextBadgeLevel = "";

//User progress
if(isConnected()){
    //Streak
    $streak = intSQL("SELECT `streak` FROM `users` WHERE `username` = ?;", [$_COOKIE["username"]]);
    $streakCurrentBadgeLevel = getCurrentBadgeLevel($streak, $streak_badges, getString("streak_unit"));
    $streakNextBadgeLevel = getNextBadgeLevel($streak, $streak_badges, getString("streak_unit"));
    //Points
    $points = intSQL("SELECT `points` FROM `users` WHERE `username` = ?;", [$_COOKIE["username"]]);
    $pointsCurrentBadgeLevel = getCurrentBadgeLevel($points, $points_badges, getString("points_unit"));
    $pointsNextBadgeLevel = getNextBadgeLevel($points, $points_badges, getString("points_unit"));
    //Predictions created
    $predictionsCreated = intSQL("SELECT `predictionsCreated` FROM `users` LEFT JOIN (SELECT `user`, COUNT(*) AS `predictionsCreated` FROM `predictions` GROUP BY `user`) `predictions2` ON `users`.`username` = `predictions2`.`user` WHERE `username` = ?;", [$_COOKIE["username"]]);
    $predictionsCreatedCurrentBadgeLevel = getCurrentBadgeLevel($predictionsCreated, $predictionsCreated_badges, getString("predictions_unit"));
    $predictionsCreatedNextBadgeLevel = getNextBadgeLevel($predictionsCreated, $predictionsCreated_badges, getString("predictions_unit"));
    //Bets
    $bets = intSQL("SELECT `bets` FROM `users` LEFT JOIN (SELECT `user`, COUNT(*) AS `bets` FROM `votes` GROUP BY `user`) `votes2` ON `users`.`username` = `votes2`.`user` WHERE `username` = ?;", [$_COOKIE["username"]]);
    $betsCurrentBadgeLevel = getCurrentBadgeLevel($bets, $bets_badges, getString("bets_unit"));
    $betsNextBadgeLevel = getNextBadgeLevel($bets, $bets_badges, getString("bets_unit"));
    //Points spent
    $pointsSpent = intSQL("SELECT `pointsSpent` FROM `users` LEFT JOIN (SELECT `user`, SUM(`points`) AS `pointsSpent` FROM `votes` GROUP BY `user`) `votes2` ON `users`.`username` = `votes2`.`user` WHERE `username` = ?;", [$_COOKIE["username"]]);
    $pointsSpentCurrentBadgeLevel = getCurrentBadgeLevel($pointsSpent, $pointsSpent_badges, getString("points_unit"));
    $pointsSpentNextBadgeLevel = getNextBadgeLevel($pointsSpent, $pointsSpent_badges, getString("points_unit"));
    //Bets won
    $betsWon = intSQL("SELECT `correct_vote_count` FROM `users` LEFT JOIN (SELECT votes.user, COUNT(*) AS correct_vote_count FROM votes JOIN predictions ON votes.prediction = predictions.id WHERE votes.choice = predictions.answer GROUP BY votes.user) correct_votes ON users.username = correct_votes.user WHERE `username` = ?;", [$_COOKIE["username"]]);
    $betsWonCurrentBadgeLevel = getCurrentBadgeLevel($betsWon, $betsWon_badges, getString("bets_unit"));
    $betsWonNextBadgeLevel = getNextBadgeLevel($betsWon, $betsWon_badges, getString("bets_unit"));
}

//Functions
/** Get current badge level
 * @param int $stat the stat to check
 * @param array $tab the array of badges
 * @param string $unit the unit of the stat
 * @return string the current badge level
 */
function getCurrentBadgeLevel(int $stat, array $tab, string $unit){
    if($stat < $tab[0]) return getString("badges_none");
    if($stat < $tab[1]) return getString("badges_bronze") . "<br><small>" . displayInt($stat) . " / " . displayInt($tab[0]) . " " . $unit . "</small>";
    if($stat < $tab[2]) return getString("badges_silver") . "<br><small>" . displayInt($stat) . " / " . displayInt($tab[1]) . " " . $unit . "</small>";
    if($stat < $tab[3]) return getString("badges_gold") . "<br><small>" . displayInt($stat) . " / " . displayInt($tab[2]) . " " . $unit . "</small>";
    if($stat >= $tab[3]) return getString("badges_diamond") . "<br><small>" . displayInt($stat) . " / " . displayInt($tab[3]) . " " . $unit . "</small>";
    return "";
}

/**
 * Get next badge level
 * @param int $stat the stat to check
 * @param array $tab the array of badges
 * @param string $unit the unit of the stat
 * @return string the next badge level
 */
function getNextBadgeLevel(int $stat, array $tab, string $unit){
    if($stat < $tab[0]) return getString("badges_bronze") . "<br>" . getString("badges_progress", [displayInt($tab[0] - $stat), $unit]) . "<br><small>(" . displayInt($stat) . " / " . displayInt($tab[0]) . ")</small>";
    if($stat < $tab[1]) return getString("badges_silver") . "<br>" . getString("badges_progress", [displayInt($tab[1] - $stat), $unit]) . "<br><small>(" . displayInt($stat) . " / " . displayInt($tab[1]) . ")</small>";
    if($stat < $tab[2]) return getString("badges_gold") . "<br>" . getString("badges_progress", [displayInt($tab[2] - $stat), $unit]) . "<br><small>(" . displayInt($stat) . " / " . displayInt($tab[2]) . ")</small>";
    if($stat < $tab[3]) return getString("badges_diamond") . "<br>" . getString("badges_progress", [displayInt($tab[3] - $stat), $unit]) . "<br><small>(" . displayInt($stat) . " / " . displayInt($tab[3]) . ")</small>";
    if($stat >= $tab[3]) return getString("badges_congratulations");
    return "";
}

/**
 * Display full static badge row
 * @param string $title String key for the title
 * @param int $value Current value
 * @param string $svg SVG keyword (ex. "calendar" for "svg/badges/calendarBronze.svg")
 * @param array $goals Array of goals
 * @param string $unit_string_key String key for the unit
 * @param string $currentLevel String which fills the current level column
 * @param string $nextLevel String which fills the next level column
 * @return void
 */
function fullStaticBadgeRow(string $title, int $value, string $svg, array $goals, string $unit_string_key, string $currentLevel, string $nextLevel){
    echo "<tr><td" . ($value >= $goals[0] ? " class=\"green\"" : "") . ">" . getString($title) . "</td>";
    echo "<td" . ($value >= $goals[0] ? " class=\"green\"" : "") . "><img src='svg/badges/" . $svg . "Bronze.svg' alt='" . getString("badges_bronze") . "' title='" . getString("badges_bronze") . "'><br>" . displayInt($goals[0]) . " " . getString($unit_string_key) . "</td>";
    echo "<td" . ($value >= $goals[1] ? " class=\"green\"" : "") . "><img src='svg/badges/" . $svg . "Silver.svg' alt='" . getString("badges_silver") . "' title='" . getString("badges_silver") . "'><br>" . displayInt($goals[1]) . " " . getString($unit_string_key) . "</td>";
    echo "<td" . ($value >= $goals[2] ? " class=\"green\"" : "") . "><img src='svg/badges/" . $svg . "Gold.svg' alt='" . getString("badges_gold") . "' title='" . getString("badges_gold") . "'><br>" . displayInt($goals[2]) . " " . getString($unit_string_key) . "</td>";
    echo "<td" . ($value >= $goals[3] ? " class=\"green\"" : "") . "><img src='svg/badges/" . $svg . "Diamond.svg' alt='" . getString("badges_diamond") . "' title='" . getString("badges_diamond") . "'><br>" . displayInt($goals[3]) . " " . getString($unit_string_key) . "</td>";
    if(isConnected()){
        echo "<td" . ($value >= $goals[3] ? " class=\"green\"" : "") . ">" . $currentLevel . "</td>";
        echo "<td" . ($value >= $goals[3] ? " class=\"green\"" : "") . ">" . $nextLevel . "</td>";
    } else {
        displayInviteShowProgress();
    }
    echo "</tr>";
}

/**
 * Display full dynamic badge row
 * @param string $title String key for the title
 * @param int $value Current value
 * @param string $svg SVG keyword (ex. "calendar" for "svg/badges/calendarBronze.svg")
 * @param array $top Array of top percentages
 * @param array $goals Array of goals
 * @param string $unit_string_key String key for the unit
 * @param string $currentLevel String which fills the current level column
 * @param string $nextLevel String which fills the next level column
 * @return void
 */
function fullDynamicBadgeRow(string $title, int $value, string $svg, array $top, array $goals, string $unit_string_key, string $currentLevel, string $nextLevel){
    echo "<tr><td" . ($value >= $goals[0] ? " class=\"green\"" : "") . ">" . getString($title) . "</td>";
    echo "<td" . ($value >= $goals[0] ? " class=\"green\"" : "") . "><img src='svg/badges/" . $svg . "Bronze.svg' alt='" . getString("badges_bronze") . "' title='" . getString("badges_bronze") . "'><br>" . getString("percentage_top", [displayFloat($top[0])]) . "<br><small>" . displayInt($goals[0]) . " " . getString($unit_string_key) . "</small></td>";
    echo "<td" . ($value >= $goals[1] ? " class=\"green\"" : "") . "><img src='svg/badges/" . $svg . "Silver.svg' alt='" . getString("badges_silver") . "' title='" . getString("badges_silver") . "'><br>" . getString("percentage_top", [displayFloat($top[1])]) . "<br><small>" . displayInt($goals[1]) . " " . getString($unit_string_key) . "</small></td>";
    echo "<td" . ($value >= $goals[2] ? " class=\"green\"" : "") . "><img src='svg/badges/" . $svg . "Gold.svg' alt='" . getString("badges_gold") . "' title='" . getString("badges_gold") . "'><br>" . getString("percentage_top", [displayFloat($top[2])]) . "<br><small>" . displayInt($goals[2]) . " " . getString($unit_string_key) . "</small></td>";
    echo "<td" . ($value >= $goals[3] ? " class=\"green\"" : "") . "><img src='svg/badges/" . $svg . "Diamond.svg' alt='" . getString("badges_diamond") . "' title='" . getString("badges_diamond") . "'><br>" . getString("percentage_top", [displayFloat($top[3])]) . "<br><small>" . displayInt($goals[3]) . " " . getString($unit_string_key) . "</small></td>";
    if(isConnected()){
        echo "<td" . ($value >= $goals[3] ? " class=\"green\"" : "") . ">" . $currentLevel . "</td>";
        echo "<td" . ($value >= $goals[3] ? " class=\"green\"" : "") . ">" . $nextLevel . "</td>";
    } else {
        displayInviteShowProgress();
    }
    echo "</tr>";
}

/**
 * Generate badge icon for static badges
 * @param int $value the current value
 * @param array $goals the array of goals
 * @param string $svg the SVG keyword (ex. "calendar" for "svg/badges/calendarBronze.svg")
 * @param string $name the name in the tooltip (ex. "Jours" for "Jours : 7+")
 * @return string the badge icon
 */
function checkStaticBadge(int $value, array $goals, string $svg, string $name){
    if($value < $goals[0]) return "";
    if($value < $goals[1]) return "<abbr title='" . $name . " – " . displayInt($goals[0]) . "+'><img class='user-icon' src='svg/badges/" . $svg . "Bronze.svg'></abbr>";
    if($value < $goals[2]) return "<abbr title='" . $name . " – " . displayInt($goals[1]) . "+'><img class='user-icon' src='svg/badges/" . $svg . "Silver.svg'></abbr>";
    if($value < $goals[3]) return "<abbr title='" . $name . " – " . displayInt($goals[2]) . "+'><img class='user-icon' src='svg/badges/" . $svg . "Gold.svg'></abbr>";
    if($value >= $goals[3]) return "<abbr title='" . $name . " – " . displayInt($goals[3]) . "+'><img class='user-icon' src='svg/badges/" . $svg . "Diamond.svg'></abbr>";
    return "";
}

/**
 * Generate badge icon for dynamic badges (top xx%)
 * @param int $value the current value
 * @param array $top the array of top percentages
 * @param array $goals the array of goals
 * @param string $svg the SVG keyword (ex. "points" for "svg/badges/pointsBronze.svg")
 * @param string $name the name in the tooltip (ex. "Points" for "Points : Top 10 %")
 * @return string the badge icon
 */
function checkDynamicBadge(int $value, array $top, array $goals, string $svg, string $name){
    if($value < $goals[0]) return "";
    if($value < $goals[1]) return "<abbr title='" . $name . " – " . getString("percentage_top", [displayFloat($top[0])]) . "'><img class='user-icon' src='svg/badges/" . $svg . "Bronze.svg'></abbr>";
    if($value < $goals[2]) return "<abbr title='" . $name . " – " . getString("percentage_top", [displayFloat($top[1])]) . "'><img class='user-icon' src='svg/badges/" . $svg . "Silver.svg'></abbr>";
    if($value < $goals[3]) return "<abbr title='" . $name . " – " . getString("percentage_top", [displayFloat($top[2])]) . "'><img class='user-icon' src='svg/badges/" . $svg . "Gold.svg'></abbr>";
    if($value >= $goals[3]) return "<abbr title='" . $name . " – " . getString("percentage_top", [displayFloat($top[3])]) . "'><img class='user-icon' src='svg/badges/" . $svg . "Diamond.svg'></abbr>";
    return "";
}