<?php
/**
 * Transform "Top xx%" into a value
 * @param float $percentage the percentage to check (ex. 10 for Top 10%)
 * @param string $sql the SQL query to execute
 * @return int the value
 */
function topPercentToValue(float $percentage, string $sql){
    $rawSQL = arraySQL($sql . ";");
    $count = $rawSQL?count($rawSQL):0;
    $offset = floor($count * $percentage / 100) - 1;
    if($offset < 0) return PHP_INT_MAX;
    return intSQL($sql . " LIMIT 1 OFFSET " . $offset . ";");
}

//Arrays
//Goals are defined here
$streak_badges = [7, 14, 30, 365];
$points_top = [10, 5, 1, 0.1];
$predictionsCreated_top = [10, 5, 1, 0.1];
$bets_top = [10, 5, 1, 0.1];
$pointsSpent_top = [10, 5, 1, 0.1];
//Autogenerated arrays
$points_sql = "SELECT `points` FROM `users` ORDER BY `points` DESC";
$points_badges = [];
foreach($points_top as $top){
    array_push($points_badges, topPercentToValue($top, $points_sql));
}
$predictionsCreated_sql = "SELECT `predictionsCreated` FROM `users` LEFT JOIN (SELECT `user`, COUNT(*) AS `predictionsCreated` FROM `predictions` GROUP BY `user`) `predictions2` ON `users`.`username` = `predictions2`.`user` ORDER BY `predictionsCreated` DESC";
$predictionsCreated_badges = [];
foreach($predictionsCreated_top as $top){
    array_push($predictionsCreated_badges, topPercentToValue($top, $predictionsCreated_sql));
}
$bets_sql = "SELECT `bets` FROM `users` LEFT JOIN (SELECT `user`, COUNT(*) AS `bets` FROM `votes` GROUP BY `user`) `votes2` ON `users`.`username` = `votes2`.`user` ORDER BY `bets` DESC";
$bets_badges = [];
foreach($bets_top as $top){
    array_push($bets_badges, topPercentToValue($top, $bets_sql));
}
$pointsSpent_sql = "SELECT `pointsSpent` FROM `users` LEFT JOIN (SELECT `user`, SUM(`points`) AS `pointsSpent` FROM `votes` GROUP BY `user`) `votes2` ON `users`.`username` = `votes2`.`user` ORDER BY `pointsSpent` DESC";
$pointsSpent_badges = [];
foreach($pointsSpent_top as $top){
    array_push($pointsSpent_badges, topPercentToValue($top, $pointsSpent_sql));
}

//Functions
/** Get current badge level
 * @param int $stat the stat to check
 * @param array $tab the array of badges
 * @param string $unit the unit of the stat
 * @return string the current badge level
*/
function getCurrentBadgeLevel(int $stat, array $tab, string $unit){
    if($stat < $tab[0]) return getString("badges_none");
    if($stat < $tab[1]) return getString("badges_bronze") . "<br><small>" . displayInt($stat) . " / " . displayInt($tab[0]) . " " . $unit . "</small>";
    if($stat < $tab[2]) return getString("badges_silver") . "<br><small>" . displayInt($stat) . " / " . displayInt($tab[1]) . " " . $unit . "</small>";
    if($stat < $tab[3]) return getString("badges_gold") . "<br><small>" . displayInt($stat) . " / " . displayInt($tab[2]) . " " . $unit . "</small>";
    if($stat >= $tab[3]) return getString("badges_diamond") . "<br><small>" . displayInt($stat) . " / " . displayInt($tab[3]) . " " . $unit . "</small>";
    return "";
}

/**
 * Get next badge level
 * @param int $stat the stat to check
 * @param array $tab the array of badges
 * @param string $unit the unit of the stat
 * @return string the next badge level
 */
function getNextBadgeLevel(int $stat, array $tab, string $unit){
    if($stat < $tab[0]) return getString("badges_bronze") . "<br>" . getString("badges_progress", [displayInt($tab[0] - $stat), $unit]) . "<br><small>(" . displayInt($stat) . " / " . displayInt($tab[0]) . ")</small>";
    if($stat < $tab[1]) return getString("badges_silver") . "<br>" . getString("badges_progress", [displayInt($tab[1] - $stat), $unit]) . "<br><small>(" . displayInt($stat) . " / " . displayInt($tab[1]) . ")</small>";
    if($stat < $tab[2]) return getString("badges_gold") . "<br>" . getString("badges_progress", [displayInt($tab[2] - $stat), $unit]) . "<br><small>(" . displayInt($stat) . " / " . displayInt($tab[2]) . ")</small>";
    if($stat < $tab[3]) return getString("badges_diamond") . "<br>" . getString("badges_progress", [displayInt($tab[3] - $stat), $unit]) . "<br><small>(" . displayInt($stat) . " / " . displayInt($tab[3]) . ")</small>";
    if($stat >= $tab[3]) return getString("badges_congratulations");
    return "";
}

/**
 * Generate badge row for static badges
 * @param string $svg the SVG keyword (ex. "calendar" for "svg/badges/calendarBronze.svg")
 * @param array $goals the array of goals
 * @param string $unit the unit of the stat
 * @return void
 */
function generateStaticBadgeRow(string $svg, array $goals, string $unit){
    echo "
        <td><img src='svg/badges/" . $svg . "Bronze.svg' alt='" . getString("badges_bronze") . "' title='" . getString("badges_bronze") . "'><br>" . displayInt($goals[0]) . " " . $unit . "</td>
        <td><img src='svg/badges/" . $svg . "Silver.svg' alt='" . getString("badges_silver") . "' title='" . getString("badges_silver") . "'><br>" . displayInt($goals[1]) . " " . $unit . "</td>
        <td><img src='svg/badges/" . $svg . "Gold.svg' alt='" . getString("badges_gold") . "' title='" . getString("badges_gold") . "'><br>" . displayInt($goals[2]) . " " . $unit . "</td>
        <td><img src='svg/badges/" . $svg . "Diamond.svg' alt='" . getString("badges_diamond") . "' title='" . getString("badges_diamond") . "'><br>" . displayInt($goals[3]) . " " . $unit . "</td>
    ";
}

/**
 * Generate badge row for dynamic badges
 * @param string $svg the SVG keyword (ex. "points" for "svg/badges/pointsBronze.svg")
 * @param array $top the array of top percentages
 * @param array $goals the array of goals
 * @param string $unit the unit of the stat
 * @return void
 */
function generateDynamicBadgeRow(string $svg, array $top, array $goals, string $unit){
    echo "
        <td><img src='svg/badges/" . $svg . "Bronze.svg' alt='" . getString("badges_bronze") . "' title='" . getString("badges_bronze") . "'><br>" . getString("percentage_top", [displayFloat($top[0])]) . "<br><small>" . displayInt($goals[0]) . " " . $unit . "</small></td>
        <td><img src='svg/badges/" . $svg . "Silver.svg' alt='" . getString("badges_silver") . "' title='" . getString("badges_silver") . "'><br>" . getString("percentage_top", [displayFloat($top[1])]) . "<br><small>" . displayInt($goals[1]) . " " . $unit . "</small></td>
        <td><img src='svg/badges/" . $svg . "Gold.svg' alt='" . getString("badges_gold") . "' title='" . getString("badges_gold") . "'><br>" . getString("percentage_top", [displayFloat($top[2])]) . "<br><small>" . displayInt($goals[2]) . " " . $unit . "</small></td>
        <td><img src='svg/badges/" . $svg . "Diamond.svg' alt='" . getString("badges_diamond") . "' title='" . getString("badges_diamond") . "'><br>" . getString("percentage_top", [displayFloat($top[3])]) . "<br><small>" . displayInt($goals[3]) . " " . $unit . "</small></td>
    ";
}

/**
 * Generate badge icon for static badges
 * @param int $value the current value
 * @param array $goals the array of goals
 * @param string $svg the SVG keyword (ex. "calendar" for "svg/badges/calendarBronze.svg")
 * @param string $name the name in the tooltip (ex. "Jours" for "Jours : 7+")
 * @return string the badge icon
 */
function checkStaticBadge(int $value, array $goals, string $svg, string $name){
    if($value < $goals[0]) return "";
    if($value < $goals[1]) return "<abbr title='" . $name . " – " . displayInt($goals[0]) . "+'><img class='user-icon' src='svg/badges/" . $svg . "Bronze.svg'></abbr>";
    if($value < $goals[2]) return "<abbr title='" . $name . " – " . displayInt($goals[1]) . "+'><img class='user-icon' src='svg/badges/" . $svg . "Silver.svg'></abbr>";
    if($value < $goals[3]) return "<abbr title='" . $name . " – " . displayInt($goals[2]) . "+'><img class='user-icon' src='svg/badges/" . $svg . "Gold.svg'></abbr>";
    if($value >= $goals[3]) return "<abbr title='" . $name . " – " . displayInt($goals[3]) . "+'><img class='user-icon' src='svg/badges/" . $svg . "Diamond.svg'></abbr>";
    return "";
}

/**
 * Generate badge icon for dynamic badges (top xx%)
 * @param int $value the current value
 * @param array $top the array of top percentages
 * @param array $goals the array of goals
 * @param string $svg the SVG keyword (ex. "points" for "svg/badges/pointsBronze.svg")
 * @param string $name the name in the tooltip (ex. "Points" for "Points : Top 10 %")
 * @return string the badge icon
 */
function checkDynamicBadge(int $value, array $top, array $goals, string $svg, string $name){
    if($value < $goals[0]) return "";
    if($value < $goals[1]) return "<abbr title='" . $name . " – " . getString("percentage_top", [displayFloat($top[0])]) . "'><img class='user-icon' src='svg/badges/" . $svg . "Bronze.svg'></abbr>";
    if($value < $goals[2]) return "<abbr title='" . $name . " – " . getString("percentage_top", [displayFloat($top[1])]) . "'><img class='user-icon' src='svg/badges/" . $svg . "Silver.svg'></abbr>";
    if($value < $goals[3]) return "<abbr title='" . $name . " – " . getString("percentage_top", [displayFloat($top[2])]) . "'><img class='user-icon' src='svg/badges/" . $svg . "Gold.svg'></abbr>";
    if($value >= $goals[3]) return "<abbr title='" . $name . " – " . getString("percentage_top", [displayFloat($top[3])]) . "'><img class='user-icon' src='svg/badges/" . $svg . "Diamond.svg'></abbr>";
    return "";
}